// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xqDKUCOa2ImywUJgX39uDZgoymNGpYQ',
    appId: '1:741707046142:web:9449da4ec52a959293d9af',
    messagingSenderId: '741707046142',
    projectId: 'hdbox-app',
    authDomain: 'hdbox-app.firebaseapp.com',
    storageBucket: 'hdbox-app.firebasestorage.app',
    measurementId: 'G-K3LVZWQJ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBis_f7vuQV7Wz-b5ut6cs9hj6eBxEJ610',
    appId: '1:741707046142:android:802253232dbf43ec93d9af',
    messagingSenderId: '741707046142',
    projectId: 'hdbox-app',
    storageBucket: 'hdbox-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdlVPugQrjMFvB2i0YrY-IZH_Lc0vIbg',
    appId: '1:741707046142:ios:48d58f730721a40893d9af',
    messagingSenderId: '741707046142',
    projectId: 'hdbox-app',
    storageBucket: 'hdbox-app.firebasestorage.app',
    iosBundleId: 'com.example.hdboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdlVPugQrjMFvB2i0YrY-IZH_Lc0vIbg',
    appId: '1:741707046142:ios:48d58f730721a40893d9af',
    messagingSenderId: '741707046142',
    projectId: 'hdbox-app',
    storageBucket: 'hdbox-app.firebasestorage.app',
    iosBundleId: 'com.example.hdboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xqDKUCOa2ImywUJgX39uDZgoymNGpYQ',
    appId: '1:741707046142:web:3f31c0137eee602293d9af',
    messagingSenderId: '741707046142',
    projectId: 'hdbox-app',
    authDomain: 'hdbox-app.firebaseapp.com',
    storageBucket: 'hdbox-app.firebasestorage.app',
    measurementId: 'G-HVMR85Z59T',
  );

}